### ISSUE TITLE
TranslateFrom* argument usage

### ISSUE THREAD

**Issue by mafaca** [spacehamster/HLSLccWrapper#1]
https://github.com/spacehamster/HLSLccWrapper/blob/master/HLSLccWrapper/HLSLccWrapper.cpp#L8
and
https://github.com/spacehamster/HLSLccWrapper/blob/master/HLSLccWrapper/HLSLccWrapper.cpp#L43
doesn't use _WrappedGLLang lang_ argument

**Comment by spacehamster** [comment]
Fixed in ae97b646b890281bf77f68b20d2fec86cd0d2cab
